;-----------------------------------------------------------------------------;
;-----------------------------------------------------------------------------;
;-------------ROTATES ROOF THEN SETS THE ROOF ID ANGLE TO 0-------------------;
;-----------------------------------------------------------------------------;
;-----------------------------------------------------------------------------;
;-----------------------------------------------------------------------------;
;-----MADE BY TAMIR LIEBER----------------------------------------------------;
;-----------------------------------------------------------------------------;

(defun c:rfrot()
  (vl-load-com)
  (progn
  (vl-cmdf "rotate" (ssget) "" PAUSE PAUSE PAUSE PAUSE PAUSE "")
  (vla-sendcommand
		  		(vla-get-activedocument
		  			(vlax-get-acad-object)
 		  		) ;_ vla-get-activedocument
		  		"ROTID"
		  	)
  (vla-sendcommand
		  		(vla-get-activedocument
		  			(vlax-get-acad-object)
 		  		) ;_ vla-get-activedocument
		  		" "
			)
  )
)
